service: leaderboards

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: offline
  region: eu-west-1
  profile: serverless
  environment: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["LeaguesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["UserLeaguesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["CompetitorDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["MatchesDynamoDBTable", "Arn" ] }

package:
  exclude:
    - ".*/**"

custom:
  dynamodb:
    start:
      migrate: true
      seed: true
    seed:
      leagues:
        sources:
          - table: leaderboards-offline-leagues
            sources: [./migrations/leagues.json]
          - table: leaderboards-offline-user-leagues
            sources: [./migrations/user_leagues.json]
          - table: leaderboards-offline-competitors
            sources: [./migrations/competitors.json]
    stages:
      - offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    LeaguesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: leaguePool
            AttributeType: S
          - AttributeName: leagueId
            AttributeType: S
        KeySchema:
          - AttributeName: leaguePool
            KeyType: HASH
          - AttributeName: leagueId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'leaderboards-${opt:stage, self:provider.stage}-leagues'
    UserLeaguesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: leagueId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: leagueId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'leaderboards-${opt:stage, self:provider.stage}-user-leagues'
    CompetitorDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: leagueId
            AttributeType: S
          - AttributeName: competitorId
            AttributeType: S
        KeySchema:
          - AttributeName: leagueId
            KeyType: HASH
          - AttributeName: competitorId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
        TableName: 'leaderboards-${opt:stage, self:provider.stage}-competitors'
    MatchesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: leagueId
            AttributeType: S
          - AttributeName: matchId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: leagueId
            KeyType: HASH
          - AttributeName: matchId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: createdAt-index
            KeySchema:
              - AttributeName: leagueId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'leaderboards-${opt:stage, self:provider.stage}-match-records'
    MatchContestantsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: leagueId
            AttributeType: S
          - AttributeName: matchContestantId
            AttributeType: S
        KeySchema:
          - AttributeName: leagueId
            KeyType: HASH
          - AttributeName: matchContestantId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'leaderboards-${opt:stage, self:provider.stage}-match-contestants'
